Refactor mobile webservice doc
pusheco/pushe-docs pull request #32
Opened 2020-03-03 11:20 UTC by amirhaa

2020-03-10 19:43 UTC, mahdi-malv requested changes
**Homepage** of Mobile-API refers to `/docs/mobile-api/authentication`.
By refactor, you don't mean replace the old one as well?

2020-03-14 12:20 UTC, vahid-amintabar commented
@amirhaa دکمه های next و previous پایین صفحه لینکشون درسته ولی متنشون همه یه چیزه و اشتباهه

2020-03-14 12:30 UTC, vahid-amintabar reviewed
در این سمپل کدهایی که برای ارسال اعلان نوشتی، اگر ارسال موفق باشه، جواب سرور رو پرینت می کنی. به نظرم بهتره که در این حالت statusـcode رو پرینت کنی یا بگی از ۲۰۰ بود چاپ کنه که موفق بود ارسال

2020-03-14 12:30 UTC, vahid-amintabar commented on docs/mobile-webservice/intro.md
> +در این نوع **آمار اعلان فرستاده شده ذخیره نمی‌شود** و **سرعت ارسال اعلان بسیار بالاتر** از حالت‌های دیگر است.
در این نوع، محتوا و آمار اعلان فرستاده شده ...

2020-03-14 12:30 UTC, vahid-amintabar commented on docs/mobile-webservice/get-app-id.md
> +![console get app id](/img/webservice/console-app-id.png)
در این عکس app_id و package_name یکسانه. خوب بود که یه نمونه متفاوت می گذاشتی

2020-03-14 12:53 UTC, vahid-amintabar reviewed
در صفحه توضیحات کلیدها. یه سری ها ۰۰۰۰۰۰ دارند. اونا رو نمی دونستی چیه؟

2020-03-14 12:53 UTC, vahid-amintabar commented on docs/mobile-webservice/filtered-notification.md
> +    ‍`lte`, `wifi`
`lte` غلطه. درستش `data‍` هست

2020-03-14 12:53 UTC, vahid-amintabar commented on docs/web-webservice/notification-keys.md
> +`app_id`
طبق آخرین صحبت قرار بود که app_ids باشه، درسته؟

2020-03-14 12:53 UTC, vahid-amintabar commented on docs/web-webservice/notification-keys.md
> +**نوع مقدار**: رشته string
یه اشاره ای به url بودنش نکنیم اینجا؟

2020-03-14 12:55 UTC, vahid-amintabar commented
جدول کدهای فیرموورک ها قدیمیه.

2020-05-11 13:01 UTC, mahdi-malv commented on docs/mobile-api/filtered-notification.md
> +**با مراجعه به [راهنمای اندروید استودیو](/docs/android-studio/intro) و یا پلتفرم مورد نظرتان در پوشه می‌توانید نحوه دریافت این کلیدها را مشاهده کنید.**
<div dir='rtl'>

به نظرم خوبه اینجا مستقیم به بخش شناسه رفرنس داده بشه

</div>

https://docs.pushe.co/docs/android-studio/unification#%DB%8C%DA%A9%D8%AA%D8%A7%DB%8C%DB%8C-%D8%B4%D9%86%D8%A7%D8%B3%D9%87%D9%87%D8%A7

2020-05-11 13:01 UTC, mahdi-malv commented on docs/mobile-api/filtered-notification.md
> +        این شناسه توسط اندروید به کاربران اختصاص داده می‌شود و در واقع معادل Android Id می‌باشد. در گوشی‌های با سیستم عامل پایین‌تر از اندروید ۸، شناسه‌ی Android ID کاربر بین تمامی اپلیکیشن‌های نصب ش
<div dir='rtl'>

با توجه به اینکه چنتا پلتفرم داریم خوبه که یه مالتی‌تب باشه که هر پلتفرم اسنیپت خودش رو داشته باشه اینجا

</div>

### Tab#1
**Flutter**
```dart
// pushe_flutter: 2.1.1 or higher
var deviceId = await Pushe.getDeviceId();
// 2.1.0 and lower
var deviceId = await Pushe.getAndroidId();
```

### Tab#2
**Android studio**
```kt
// Pushe v2.1.1 or higher
val deviceId = Pushe.getDeviceId()
// Pushe v2.1.0 or lower
val deviceId = Pushe.getAndroidId()
```

And ...

<div dir='rtl'>

می‌تونیم یه ضرب این کد رو قبل ریلیز بذاریم و یا اینکه وایسیم ریلیز شد توی تسک داکش بیاد.
</div>

2020-05-16 07:38 UTC, closed without merging